Check version uniqueness

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -47,6 +47,13 @@ jobs:
         versionFile: pinecone/__version__ 
         bumpType: ${{ github.event.inputs.releaseLevel }}
 
+    - name: Verify unique release number
+      run: |
+        if git tag -l | grep -q ${{ steps.bump.outputs.VERSION_TAG }}; then
+          echo "Tag ${{ steps.bump.outputs.VERSION_TAG }} already exists, aborting"
+          exit 1
+        fi
+
     - name: Commit and tag version bump
       id: tag_release
       run: |
